### PR TITLE
Drkey feature PR2

### PR DESCRIPTION
**Pull request by JordiSubira**
2nd PR among several in order to port drkey feature to scionlab. Most of the features were first introduced in https://github.com/netsec-ethz/scion/pull/63.

go/lib/drkey. (2/3)

Some changes in this PR:

- Added AS->Host, Host -> Host to the Standard derivation UT.
- Little fixes in other UT (to review).

---
This change is [Reviewable](https://reviewable.io/reviews/juagargi/scion/4)

### CODE REVIEW

**Review by juagargi — CHANGES_REQUESTED** [review]
Don't forget to run `make gazelle`

> Reviewed 1 of 8 files at r1, 2 of 4 files at r2, 1 of 2 files at r4, 5 of 5 files at r5, 1 of 7 files at r6, 4 of 4 files at r8, 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/4#-:-M5qpfyf6d4WofeEXM9S:b-c2weeq)* status: 15 of 18 files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

___
*[go/lib/drkey/exchange/suite_test.go, line 32 at r10](https://reviewable.io/reviews/juagargi/scion/4#-M5qrP8M8mETKAhyWUn8:-M5qrP8M8mETKAhyWUn9:b-z5ud6u) ([raw file](https://github.com/juagargi/scion/blob/74220697c2922a1d132d6b97f7475b1179f289e3/go/lib/drkey/exchange/suite_test.go#L32)):*
> ```Go
> 	lvl1 := genLvl1Key(t)
> 	sndPubKey, sndPrivKey, err := scrypto.GenKeyPair(scrypto.Curve25519xSalsa20Poly1305)
> 	if err != nil {
> ```

use `testify/require`: `require.NoError`
___
*[go/lib/drkey/exchange/suite_test.go, line 52 at r10](https://reviewable.io/reviews/juagargi/scion/4#-M5qrwDA4Hvf33wx6v9t:-M5qrwDA4Hvf33wx6v9u:b-l9ffhg) ([raw file](https://github.com/juagargi/scion/blob/74220697c2922a1d132d6b97f7475b1179f289e3/go/lib/drkey/exchange/suite_test.go#L52)):*
> ```Go
> 	}
> 
> 	if !(lvl1.Lvl1Meta.SrcIA.Equal(gotLvl1.Lvl1Meta.SrcIA)) {
> ```

use `testify` wherever you can in our new UTs.

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/4)* status: 1 of 19 files reviewed, 2 unresolved discussions (waiting on @juagargi)

___
*[go/lib/drkey/exchange/suite_test.go, line 32 at r10](https://reviewable.io/reviews/juagargi/scion/4#-M5qrP8M8mETKAhyWUn8:-M5wCqR4-ibncUVbJZYf:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/74220697c2922a1d132d6b97f7475b1179f289e3/go/lib/drkey/exchange/suite_test.go#L32)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

use `testify/require`: `require.NoError`
</blockquote></details>

Done.
___
*[go/lib/drkey/exchange/suite_test.go, line 52 at r10](https://reviewable.io/reviews/juagargi/scion/4#-M5qrwDA4Hvf33wx6v9t:-M5wCrBm6qcUKCrox2zS:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/74220697c2922a1d132d6b97f7475b1179f289e3/go/lib/drkey/exchange/suite_test.go#L52)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

use `testify` wherever you can in our new UTs.
</blockquote></details>

Done.

**Review by juagargi — CHANGES_REQUESTED** [review]
needs rebase (drop existing commits)

> Reviewed 1 of 4 files at r12, 2 of 5 files at r15, 2 of 7 files at r17, 4 of 4 files at r19, 4 of 4 files at r22.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/4#-:-M69pxKnDY09LXm6H9P3:bgk5zlx)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @juagargi)

___
*[go.sum, line 131 at r22](https://reviewable.io/reviews/juagargi/scion/4#-M69oayIDdrihX0jmQmH:-M69oayIDdrihX0jmQmI:b-mkw6rb) ([raw file](https://github.com/juagargi/scion/blob/e7f912ab1a60ced045a030d77edb2d62f9a84c05/go.sum#L131)):*
> ```
> github.com/spf13/pflag v1.0.1-0.20180403115518-1ce0cc6db402/go.mod h1:DYY7MBk1bdzusC3SYhjObp+wFpr4gzcvqqNjLnInEg4=
> github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
> github.com/stretchr/objx v0.1.1 h1:2vfRuCMp5sSVIDSqO8oNnWJq7mPa6KVP3iPIwFBuy8A=
> ```

I think there's no reason to need to update `go.sum`
___
*[go/lib/drkey/protocol/protocol_test.go, line 70 at r22](https://reviewable.io/reviews/juagargi/scion/4#-M69pL6V9nRYKS4lDE0P:-M69pL6WAugIzZ-oOt2U:bak1c5d) ([raw file](https://github.com/juagargi/scion/blob/e7f912ab1a60ced045a030d77edb2d62f9a84c05/go/lib/drkey/protocol/protocol_test.go#L70)):*
> ```Go
> 		}
> 		hexKey := hex.EncodeToString(lvl2.Key)
> 		if hexKey != key {
> ```

use `testify` in new UTs
___
*[go/lib/drkey/protocol/standard.go, line 37 at r22](https://reviewable.io/reviews/juagargi/scion/4#-M69pa3F-JyaCvGGIV-d:-M69pa3F-JyaCvGGIV-e:b-o5wsr8) ([raw file](https://github.com/juagargi/scion/blob/e7f912ab1a60ced045a030d77edb2d62f9a84c05/go/lib/drkey/protocol/standard.go#L37)):*
> ```Go
> func (p Standard) DeriveLvl2(meta drkey.Lvl2Meta, key drkey.Lvl1Key) (drkey.Lvl2Key, error) {
> 	h, err := scrypto.InitMac([]byte(key.Key))
> 	if err != nil {
> ```

use testify

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/4)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @juagargi)

___
*[go/lib/drkey/protocol/standard.go, line 37 at r22](https://reviewable.io/reviews/juagargi/scion/4#-M69pa3F-JyaCvGGIV-d:-M6AWzFiAjOfhyCnxdWs:bqvk5y) ([raw file](https://github.com/juagargi/scion/blob/e7f912ab1a60ced045a030d77edb2d62f9a84c05/go/lib/drkey/protocol/standard.go#L37)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

use testify
</blockquote></details>

Must we use testify outside UT?

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/4)* status: 14 of 19 files reviewed, 2 unresolved discussions (waiting on @JordiSubira and @juagargi)

___
*[go/lib/drkey/protocol/standard.go, line 37 at r22](https://reviewable.io/reviews/juagargi/scion/4#-M69pa3F-JyaCvGGIV-d:-M6EQhD074OsM7SR-QSs:bwqzerw) ([raw file](https://github.com/juagargi/scion/blob/e7f912ab1a60ced045a030d77edb2d62f9a84c05/go/lib/drkey/protocol/standard.go#L37)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Must we use testify outside UT?
</blockquote></details>

oh God no, my mistake. I _think_ I mistook the file as a UT. It is fine as it is.

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/4)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @juagargi)

___
*[go.sum, line 131 at r22](https://reviewable.io/reviews/juagargi/scion/4#-M69oayIDdrihX0jmQmH:-M6FfsdlDyXgJlh4v8xD:bp3aow6) ([raw file](https://github.com/juagargi/scion/blob/e7f912ab1a60ced045a030d77edb2d62f9a84c05/go.sum#L131)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

I think there's no reason to need to update `go.sum`
</blockquote></details>

Reverted.
___
*[go/lib/drkey/protocol/protocol_test.go, line 70 at r22](https://reviewable.io/reviews/juagargi/scion/4#-M69pL6V9nRYKS4lDE0P:-M6Fg0iu5PE4OopiafZR:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/e7f912ab1a60ced045a030d77edb2d62f9a84c05/go/lib/drkey/protocol/protocol_test.go#L70)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

use `testify` in new UTs
</blockquote></details>

Done.

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r25, 2 of 4 files at r28, 3 of 3 files at r29.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/4#-:-M72gzKA95Ew6SqLLVlN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
