### PR TITLE
Drkey port pr8

### PR DESCRIPTION
**Pull request by JordiSubira**
8th PR among several in order to port drkey feature to scionlab. Most of the features were first introduced in netsec-ethz#63.

DRKey feature in go/sciond/.

Some changes, including:
- Adapting drkey handler
- Adapting to metrics
- Refactoring name for config.go drkeystorage
- Apating drkey handler initialization in main.go

---
This change is [Reviewable](https://reviewable.io/reviews/juagargi/scion/14)

### CODE REVIEW

**Review by juagargi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/14)* status: 10 of 21 files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[go/sciond/internal/drkey/client_store.go, line 82 at r1](https://reviewable.io/reviews/juagargi/scion/14#-M93KRwf4uzDqGGJXwrx:-M93KRwf4uzDqGGJXwry:b-v5zdq8) ([raw file](https://github.com/juagargi/scion/blob/b6f2b7b75a19fa324807fc03ec602de34108c6ba/go/sciond/internal/drkey/client_store.go#L82)):*
> ```Go
> 	k = rep.ToKey(meta)
> 	if err = s.db.InsertLvl2Key(ctx, k); err != nil {
> 		logger.Error("[DRKey ClientStore] Could not insert level 2 in DB", err)
> ```

build is broken: needs a string label before `err`
```go
logger.Error("[DRKey ClientStore] Could not insert level 2 in DB", "error", err)
```
But from the context I assume that you wanted to return an error there, with `serrors.WrapStr`

**Review by juagargi — COMMENTED** [review]
> Reviewed 5 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/14)* status: 15 of 21 files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

**Review by juagargi — COMMENTED** [review]
just one minor thing

> Reviewed 6 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/14#-:-M93RYPW17Jvk6X4Ib1Z:b-2omx0m)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

**Review by juagargi — COMMENTED** [review]
and now that I try it, please also fix problems from the linter (run `scion.sh lint`)

> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/14#-:-M93Rr7x72fS1EXSShI0:byaohn5)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/14)* status: 7 of 20 files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[go/sciond/internal/drkey/client_store.go, line 82 at r1](https://reviewable.io/reviews/juagargi/scion/14#-M93KRwf4uzDqGGJXwrx:-M9U8UQYC2v4YmumL2f2:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/b6f2b7b75a19fa324807fc03ec602de34108c6ba/go/sciond/internal/drkey/client_store.go#L82)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

build is broken: needs a string label before `err`
```go
logger.Error("[DRKey ClientStore] Could not insert level 2 in DB", "error", err)
```
But from the context I assume that you wanted to return an error there, with `serrors.WrapStr`
</blockquote></details>

Done.

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/14#-:-M9ZzZOpA6U03HJNBB2c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
