### PR TITLE
Drkey feature PR1

### PR DESCRIPTION
**Pull request by JordiSubira**
1st PR among several in order to port drkey feature to scionlab. Most of the features were first introduced in https://github.com/netsec-ethz/scion/pull/63.

Next 3 PRs include go/lib/drkey. (1/3)

Some minor changes in this PR:

- Refactoring Epoch based on Validity period https://github.com/scionproto/scion/pull/2842/files.
- Added SV derivation UT.

---
This change is [Reviewable](https://reviewable.io/reviews/juagargi/scion/3)

### CODE REVIEW

**Review by juagargi — CHANGES_REQUESTED** [review]
all good, just some UTs missing

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/3#-:-M51G1wBAzWt94Y4eaEC:b8h1eh9)* status: all files reviewed, 3 unresolved discussions (waiting on @JordiSubira)

___
*[go/lib/drkey/secret_value.go, line 48 at r1](https://reviewable.io/reviews/juagargi/scion/3#-M51Dhck1OgIMml8k0R0:-M51Dhck1OgIMml8k0R1:bjblriy) ([raw file](https://github.com/juagargi/scion/blob/bff0d136668a5be8f32b06e6fc265e20c443e1f8/go/lib/drkey/secret_value.go#L48)):*
> ```Go
> 
> // DeriveSV constructs a valid SV. asSecret is typically the AS master secret.
> func DeriveSV(meta SVMeta, asSecret common.RawBytes) (SV, error) {
> ```

I was told we should not be using `RawBytes` anymore, just `[]byte`. This applies everywhere, not just here.
___
*[go/lib/drkey/secret_value_test.go, line 26 at r1](https://reviewable.io/reviews/juagargi/scion/3#-M51E5kU93vKVVHtgNjf:-M51E5kU93vKVVHtgNjg:b8hdfd8) ([raw file](https://github.com/juagargi/scion/blob/bff0d136668a5be8f32b06e6fc265e20c443e1f8/go/lib/drkey/secret_value_test.go#L26)):*
> ```Go
> func TestDeriveSV(t *testing.T) {
> 	meta := SVMeta{NewEpoch(0, 1)}
> 	asSecret := common.RawBytes{0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7}
> ```

use our `xtest.MustParseHexString`
___
*[go/lib/drkey/suite.go, line 15 at r1](https://reviewable.io/reviews/juagargi/scion/3#-M51F36A8Yvx3h0-cfwK:-M51F36A8Yvx3h0-cfwL:bem81bz) ([raw file](https://github.com/juagargi/scion/blob/bff0d136668a5be8f32b06e6fc265e20c443e1f8/go/lib/drkey/suite.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package drkey
> ```

we should add a UT to cover these two functions

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/3)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @juagargi)

___
*[go/lib/drkey/secret_value.go, line 48 at r1](https://reviewable.io/reviews/juagargi/scion/3#-M51Dhck1OgIMml8k0R0:-M57pMpS9QfHInQLmuIY:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/bff0d136668a5be8f32b06e6fc265e20c443e1f8/go/lib/drkey/secret_value.go#L48)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

I was told we should not be using `RawBytes` anymore, just `[]byte`. This applies everywhere, not just here.
</blockquote></details>

Done.
___
*[go/lib/drkey/secret_value_test.go, line 26 at r1](https://reviewable.io/reviews/juagargi/scion/3#-M51E5kU93vKVVHtgNjf:-M57pNnx1Y7f4whfJJTY:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/bff0d136668a5be8f32b06e6fc265e20c443e1f8/go/lib/drkey/secret_value_test.go#L26)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

use our `xtest.MustParseHexString`
</blockquote></details>

Done.
___
*[go/lib/drkey/suite.go, line 15 at r1](https://reviewable.io/reviews/juagargi/scion/3#-M51F36A8Yvx3h0-cfwK:-M57pQ262DcoNvYo4Vp9:bf3qvzj) ([raw file](https://github.com/juagargi/scion/blob/bff0d136668a5be8f32b06e6fc265e20c443e1f8/go/lib/drkey/suite.go#L15)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

we should add a UT to cover these two functions
</blockquote></details>

These two functions have been moved out to `exchange` package. UT can be found in https://github.com/juagargi/scion/pull/4

**Review by juagargi — CHANGES_REQUESTED** [review]
It all looks good. Just minor things:
- modify the copyright header of new files to read 2020.
- run `make gazelle`

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/3#-:-M5qpDdT0qe8Gclf1gLF:b-u0r09l)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by juagargi — COMMENTED** [review]
- and (optionally) please change the user.email so it points to your github user

> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/3#-:-M5quvOD5FOV1QlnodFi:b4cvhs7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by juagargi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/3#-:-M69nA701On_znPNJzIl:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
