### PR TITLE
Fix incorrect queue fill level

### PR DESCRIPTION
**Pull request by joelfischerr**
Also fixes some other small things

---
This change is [Reviewable](https://reviewable.io/reviews/juagargi/scion/9)

### CODE REVIEW

**Review by juagargi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/9)* status: all files reviewed, 2 unresolved discussions (waiting on @joelfischerr)

___
*[go/border/qos/qos.go, line 205 at r1](https://reviewable.io/reviews/juagargi/scion/9#-M71yw-y5tUyjoTvUr5g:-M71yw-z2xwDwhrUquzT:b3mkrtr) ([raw file](https://github.com/juagargi/scion/blob/c8ed87e7e9f66316ac2d530446e5c6849dc8d485/go/border/qos/qos.go#L205)):*
> ```Go
> 	}
> 
> 	// *qosConfig.schedul.GetMessages() <- true
> ```

remove commented out line
___
*[go/border/qos/scheduler/wrrScheduler.go, line 117 at r1](https://reviewable.io/reviews/juagargi/scion/9#-M71zooZ4cNUOMrS_EBv:-M71zoo_EMYhXZXM8xoE:b-lgcom0) ([raw file](https://github.com/juagargi/scion/blob/c8ed87e7e9f66316ac2d530446e5c6849dc8d485/go/border/qos/scheduler/wrrScheduler.go#L117)):*
> ```Go
> }
> 
> var amount0 int
> ```

why is it global to package? why not in the struct?

**Review by joelfischerr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/9)* status: all files reviewed, 2 unresolved discussions (waiting on @juagargi)

___
*[go/border/qos/qos.go, line 205 at r1](https://reviewable.io/reviews/juagargi/scion/9#-M71yw-y5tUyjoTvUr5g:-M720B2X-uCGgbJ-hWA7:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/c8ed87e7e9f66316ac2d530446e5c6849dc8d485/go/border/qos/qos.go#L205)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

remove commented out line
</blockquote></details>

Done.
___
*[go/border/qos/scheduler/wrrScheduler.go, line 117 at r1](https://reviewable.io/reviews/juagargi/scion/9#-M71zooZ4cNUOMrS_EBv:-M720RteE5vCwi_FtoNH:bxmjomt) ([raw file](https://github.com/juagargi/scion/blob/c8ed87e7e9f66316ac2d530446e5c6849dc8d485/go/border/qos/scheduler/wrrScheduler.go#L117)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

why is it global to package? why not in the struct?
</blockquote></details>

It is used in raterrScheduler.go as well

**Review by juagargi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/9)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @joelfischerr and @juagargi)

___
*[go/border/qos/scheduler/wrrScheduler.go, line 117 at r1](https://reviewable.io/reviews/juagargi/scion/9#-M71zooZ4cNUOMrS_EBv:-M72144w32coN_s3fY1N:b-32d7w) ([raw file](https://github.com/juagargi/scion/blob/c8ed87e7e9f66316ac2d530446e5c6849dc8d485/go/border/qos/scheduler/wrrScheduler.go#L117)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

It is used in raterrScheduler.go as well
</blockquote></details>

in `raterrScheduler.go` there is a new variable, with the same name but a new one nonetheless.

**Review by joelfischerr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/9)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[go/border/qos/scheduler/wrrScheduler.go, line 117 at r1](https://reviewable.io/reviews/juagargi/scion/9#-M71zooZ4cNUOMrS_EBv:-M724RMD5R-cgaamMo_o:brnvn8n) ([raw file](https://github.com/juagargi/scion/blob/c8ed87e7e9f66316ac2d530446e5c6849dc8d485/go/border/qos/scheduler/wrrScheduler.go#L117)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

in `raterrScheduler.go` there is a new variable, with the same name but a new one nonetheless.
</blockquote></details>

Done. Oh you're right, I moved into the struct

**Review by juagargi — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
