### PR TITLE
Drkey feature PR3

### PR DESCRIPTION
**Pull request by JordiSubira**
3rd PR among several in order to port drkey feature to scionlab. Most of the features were first introduced in netsec-ethz#63.

go/lib/drkey. (3/3)

Some changes in this PR:

- Refactoring to use Epoch based on Validity period https://github.com/scionproto/scion/pull/2842/files

---
This change is [Reviewable](https://reviewable.io/reviews/juagargi/scion/5)

### CODE REVIEW

**Review by juagargi — CHANGES_REQUESTED** [review]
Small changes:
- rebase
- `make gazelle`
- copyright to 2020

> Reviewed 3 of 8 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 6 of 7 files at r5, 1 of 1 files at r6, 1 of 5 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/5#-:-M5qvb5g0gORNgQaYHQ5:b-ikc39u)* status: 20 of 21 files reviewed, 3 unresolved discussions (waiting on @JordiSubira)

___
*[go/lib/drkey/drkeydbsqlite/common.go, line 14 at r8](https://reviewable.io/reviews/juagargi/scion/5#-M5qyHLU2IU4lN2XenvZ:-M5qyHLU2IU4lN2Xenv_:bjwcrlm) ([raw file](https://github.com/juagargi/scion/blob/3db0d64fc1a436588a5caedce383ee97106b6bb8/go/lib/drkey/drkeydbsqlite/common.go#L14)):*
> ```Go
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

rename the file to something more clarifying, like common_db or base_db
___
*[go/lib/drkey/drkeydbsqlite/common.go, line 37 at r8](https://reviewable.io/reviews/juagargi/scion/5#-M5qxPPPDbGMqQihXPzF:-M5qxPPPDbGMqQihXPzG:b50qxo2) ([raw file](https://github.com/juagargi/scion/blob/3db0d64fc1a436588a5caedce383ee97106b6bb8/go/lib/drkey/drkeydbsqlite/common.go#L37)):*
> ```Go
> 	Lvl1SchemaVersion = 1
> 	// Lvl1Schema is the SQLite database layout.
> 	Lvl1Schema = `
> ```

schemas should probably go to their specialized files `lvl1db` and `lvl2db`
___
*[go/lib/drkey/drkeydbsqlite/common.go, line 75 at r8](https://reviewable.io/reviews/juagargi/scion/5#-M5qyEHf4mLeI74sGEk8:-M5qyEHf4mLeI74sGEk9:b-z5li6x) ([raw file](https://github.com/juagargi/scion/blob/3db0d64fc1a436588a5caedce383ee97106b6bb8/go/lib/drkey/drkeydbsqlite/common.go#L75)):*
> ```Go
> 	db *sql.DB
> }
> ```

add `var _ drkey.BaseDB = (*dbBaseBackend)(nil)`

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/5)* status: 1 of 24 files reviewed, 3 unresolved discussions (waiting on @juagargi)

___
*[go/lib/drkey/drkeydbsqlite/common.go, line 14 at r8](https://reviewable.io/reviews/juagargi/scion/5#-M5qyHLU2IU4lN2XenvZ:-M60lV9MAI6Cs3W9GHcF:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/3db0d64fc1a436588a5caedce383ee97106b6bb8/go/lib/drkey/drkeydbsqlite/common.go#L14)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

rename the file to something more clarifying, like common_db or base_db
</blockquote></details>

Done.
___
*[go/lib/drkey/drkeydbsqlite/common.go, line 37 at r8](https://reviewable.io/reviews/juagargi/scion/5#-M5qxPPPDbGMqQihXPzF:-M60lVmc491PWfpYDQsa:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/3db0d64fc1a436588a5caedce383ee97106b6bb8/go/lib/drkey/drkeydbsqlite/common.go#L37)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

schemas should probably go to their specialized files `lvl1db` and `lvl2db`
</blockquote></details>

Done.
___
*[go/lib/drkey/drkeydbsqlite/common.go, line 75 at r8](https://reviewable.io/reviews/juagargi/scion/5#-M5qyEHf4mLeI74sGEk8:-M60lWRo9GzMuyBcJ-ve:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/3db0d64fc1a436588a5caedce383ee97106b6bb8/go/lib/drkey/drkeydbsqlite/common.go#L75)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

add `var _ drkey.BaseDB = (*dbBaseBackend)(nil)`
</blockquote></details>

Done.

**Review by juagargi — COMMENTED** [review]
Pending:
- rebase after #4 (drop existing commits)
- modify date of copyright headers (all files added in PRs #3 , #4 and this one)
Other than that, :lgtm:  !

> Reviewed 3 of 4 files at r23, 2 of 2 files at r24.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/5#-:-M69rUWoBDLGnd0w7CIM:b-jb97lm)* status: 6 of 24 files reviewed, all discussions resolved (waiting on @juagargi)

**Review by juagargi — COMMENTED** [review]
let's forget about the copyright date, only rebasing is necessary

> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/5#-:-M6FR0qBC5H0R4sAqWFc:b4bwsuu)* status: 6 of 24 files reviewed, all discussions resolved (waiting on @juagargi)

**Review by juagargi — APPROVED** [review]
> Reviewed 2 of 4 files at r10, 1 of 2 files at r12, 5 of 5 files at r13, 2 of 7 files at r15, 4 of 4 files at r17, 4 of 4 files at r20, 2 of 4 files at r23, 2 of 2 files at r24.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by juagargi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/5#-:-M732FAt3nCj-3wLno2j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
